### ISSUE TITLE
Deprecate 2KB cartridge RAM constant

### ISSUE THREAD

**Issue by sukus21** [gbdev/hardware.inc#19]
`DEF CART_SRAM_2KB   EQU 1 ; 1 incomplete bank` (from line 850)
2KB RAM carts never existed before the invention of homebrew (according to the [PanDocs](https://gbdev.io/pandocs/The_Cartridge_Header.html#0149---ram-size)).

**Comment by ISSOtm** [comment]
Fixed by #20
